name: AureliaApp
on:
  release:
    types: [created]

env:
  WEBAPP_NAME: AureliaApp    # set this to your application's name
  WEBAPP_PACKAGE_PATH: 'AureliaApp'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.x'                # set this to the node version to use

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Goto Folder
      run: cd ${{ env.WEBAPP_PACKAGE_PATH }}
    - name: npm install, build, and test
      run: |
        # Build and test the project, then
        # deploy to Azure Web App.
        npm install
        npm run build --if-present
        npm run test --if-present
   
